version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: Install dependencies and build project
      - sonarcloud/scan
      sonarqube:
    working_directory: ~/build


    docker:
      - image: sonarsource/sonar-scanner-cli

    resource_class: small
    steps:
      - run: find .
      - attach_workspace:
          at: ~/workspace
      - run: | 
          SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
          echo "Sonar branch value is: " $SONAR_BRANCH
          echo "Sonar org value is : "$SONAR_ORG
          sonar-scanner \
          -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
          -Dsonar.organization="$SONAR_ORG" \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.exclusions="**/android/**,**/ios/**" \
          -Dsonar.login="$SONAR_TOKEN" \
          -Dsonar.branch.name="$SONAR_BRANCH" \
          -Dsonar.sources="."

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
